# Variables y objetos.

**Objetivo.**
Explicar los conceptos de variables y objetos, c√≥mo es que se declaran y se usan mediante algunos ejemplos.

 <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://github.com/repomacti/introduccion_python">Introducci√≥n a Python</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://gmc.geofisica.unam.mx/luiggi">Luis Miguel de la Cruz Salas</a> is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p> 

En Python las variables:

- son **s√≠mbolos** que permiten identificar la informaci√≥n que se almacena en la memoria de la computadora,
- son **nombres** o **etiquetas** para los objetos que se crean en Python,
- se crean con ayuda del operador de asignaci√≥n `=`,
- no se tiene que establecer expl√≠citamente el tipo de dato de la variable, pues esto se realiza de manera din√°mica (**tipado din√°mico**).

## Reglas para definir variables.

Los nombres de las variables: 

* pueden contener **letras**, **n√∫meros** y **guiones bajos**,
* deben comenzar con una letra o un guion bajo,
* se distingue entre may√∫sculas y min√∫sculas, por ejemplo, `variable` y `Variable` son nombres diferentes.
* puede contener caracteres Unicode (v√©ase [Unicode](#unicode)).

    
## Variables b√°sicas.

Los siguientes ejemplos son definiciones de variables con nombres v√°lidos:

In [2]:
# el nombre de la variable con min√∫sculas, 
# el valor es de tipo cadena (usamos comillas dobles para definir una cadena)
gabo = "Gabriel Garc√≠a M√°rquez"   

# el nombre de la variable contiene un n√∫mero, 
# el valor es de tipo entero
gabo25 = 25  

# el nombre de la variable comienza con _,
# el valor es de tipo flotante
_gabo = 3.1416  

# el nombre nombre de la variable contiene may√∫sculas y min√∫sculas, 
# el valor es de tipo n√∫mero complejo: parte real + parte imaginaria (con j)
GaboComplejo = 3 + 2j  

# el nombre de la variable contiene un _, 
# el valor es de tipo L√≥gico
gabo_logico = True 

Para imprimir el contenido de las variables definidas en la celda anterior usamos la funci√≥n `print()` como sigue:

In [3]:
print(gabo)
print(gabo25)
print(_gabo)
print(GaboComplejo)
print(gabo_logico)

Gabriel Garc√≠a M√°rquez
25
3.1416
(3+2j)
True


El tipo de cada variable se obtiene usando la funci√≥n `type()`:

In [4]:
type(gabo)

str

Observa que la variable gabo es de tipo `str`.

Python proporciona los siguientes tipos de variables b√°sicas:

* num√©ricos: `int`, `float`, `complex`,
* cadenas: `str` y
* l√≥gicos: `True` y `False`.

En la notebook [02_tipos_basicos.ipynb](02_tipos_basicos.ipynb) se describen estos tipos b√°sicos en detalle.

## Funciones incorporadas (*Built-in functions*).

La funci√≥n `print()` y `type()` son dos ejemplos de **Funciones incorporadas** (*Built-in functions*) en Python, las cuales siempre est√°n disponibles para usarse en cualquier c√≥digo. Se puede consultar la lista de estas funciones en  https://docs.python.org/3/library/functions.html. 

A lo largo de estas notebooks se introducir√°n algunas de estas funciones con ejemplos sencillos. En esta notebook particularmente veremos el uso de las funciones: `print()`, `type()`, `id()`, `chr()`, `ord()`, `del()`.

La funci√≥n `print()` imprime el contenido de una variable y puede recibir varios argumentos a la vez:

In [5]:
print(gabo, gabo25)

Gabriel Garc√≠a M√°rquez 25


Se puede imprimir el resultado de una operaci√≥n:

In [6]:
print(3 * 4)

12


Tambi√©n imprime el resultado de otras funciones por ejemplo:

In [7]:
print(type(gabo))

<class 'str'>


En este caso se imprime el tipo de la variable `gabo`. Observa que se obtiene m√°s informaci√≥n, particulamente nos dice que `gabo` es un **objeto** de la clase  `'str'`. Hablaremos un poco m√°s de objetos y clases en la secci√≥n [Objetos y sus nombres](#objetos).

## Variables con may√∫sculas y min√∫sculas.

Python es sensitivo a may√∫sculas y min√∫sculas en los nombres de las variables. En el ejemplo que sigue se definen tres variables distintas:

In [8]:
pi = 3.14     
PI = 31416e-4 
Pi = 3.141592

* La variable `pi` identifica al n√∫mero flotante $3.14$.
* La variable `PI` identifica al n√∫mero flotante $31416 \times 10^{-4}$ (se usa notaci√≥n cient√≠fica `31416e-4`) que es equivalente a $3.1416$.
* La variable `Pi` identifica al n√∫mero flotante $3.141592$.

Estas tres variables son diferentes y se almacenan en lugares diferentes en la memoria de la computadora. La siguiente tabla muestra de manera esquem√°tica los conceptos de nombre, valor de la variable e identificador en memoria:

|Nombre| | Valor | id en memoria |
|--:|--|:--|:-:|
|pi |$\rightarrow$| 3.14 | 140425110809872|
|PI |$\rightarrow$| 3.1416 | 140425110112240|
|Pi |$\rightarrow$| 3.141592 | 140425110112016|

El identificador en memoria de cada variable es un n√∫mero entero. La funci√≥n `id()` permite conocer el identificador en la memoria de cada variable:

In [9]:
id(pi)

139871770615472

In [10]:
id(PI)

139871473442256

In [11]:
id(Pi)

139871769930032

Observa que cada variable tiene un n√∫mero de identificador diferente. 

Es posible imprimir el valor de la variable, su tipo y su identificador en una sola l√≠nea de c√≥digo como sigue:

In [12]:
print(pi, type(pi), id(pi))

3.14 <class 'float'> 139871770615472


<div class="alert alert-block alert-success">

### Ejercicio 1.

<font color="Black">

En la celda que sigue, escribe el siguiente c√≥digo:

```python
print(pi, type(pi), id(pi))
print(PI, type(PI), id(PI))
print(Pi, type(Pi), id(Pi))
```
<br>

Verifica que se imprime el valor, el tipo y el identificador de las variables `pi`, `PI` y `Pi` antes definidas.
</font>
</div>

In [13]:
# Escribe tu c√≥digo
### BEGIN SOLUTION
print(pi, type(pi), id(pi))
print(PI, type(PI), id(PI))
print(Pi, type(Pi), id(Pi))
### END SOLUTION

3.14 <class 'float'> 139871770615472
3.1416 <class 'float'> 139871473442256
3.141592 <class 'float'> 139871769930032


<a name="objetos">

## Objetos y sus nombres.
</a>

Python es un lenguaje **Orientado a Objetos**. 

* Todo lo que definimos ser√° un objeto de una clase.
* Una clase define atributos y m√©todos para los objetos.
* Python tiene definidas clases de las cuales es posible construir objetos.

En los ejemplos anteriores, lo que realmente est√° pasando es que se est√°n creando objetos de diferente tipo (o clase) y se les da un nombre. Por ejemplo, la siguiente declaraci√≥n:

```python
a = 1
```
crea el objeto `1` de tipo entero (`<class 'int'>`) cuyo nombre es `a`.

Si hacemos lo siguiente:

```python
b = a
```

se crea otro nombre para el mismo objeto `1`. **NO se crea otro objeto**.

<div class="alert alert-block alert-success">

### Ejercicio 2.

<font color="Black">
    
Escribe el siguiente c√≥digo y verifica que `a` y `b` tienen el mismo contenido, el mismo tipo y el mismo identificador en la memoria de la computadora:

```python
a = 1
b = a
print(a, type(a), id(a))
print(b, type(b), id(b))
```
</font>
</div>

In [14]:
# Escribe tu c√≥digo
### BEGIN SOLUTION
a = 1
b = a
print(a, type(a), id(a))
print(b, type(b), id(b))
### END SOLUTION

1 <class 'int'> 94882529782696
1 <class 'int'> 94882529782696


<div class="alert alert-block alert-info">

<b>Nota</b>. 

<font color="Black">
    
**En otros lenguajes**, por ejemplo en **lenguaje C**, un c√≥digo equivalente al del ejercicio 2 podr√≠a ser como sigue:

```
int a = 1;
int b = a;
```

En este caso, se genera el valor `1` para `a` y luego se crea otro valor `1` para `b` que es copiado de `a`, de tal manera que estas dos variables, `a` y `b` hacen referencia a lugares diferentes en la memoria.
</font>
</div>

Ahora observa y ejecuta el siguiente c√≥digo:

In [15]:
a = 1
b = a
print(a, id(a), type(a))
print(b, id(b), type(b))

b = 5.0
print(a, id(a), type(a))
print(b, id(b), type(b))

1 94882529782696 <class 'int'>
1 94882529782696 <class 'int'>
1 94882529782696 <class 'int'>
5.0 139871770615664 <class 'float'>


* Nota que inicialmente `a` y `b` tienen el mismo identificador en memoria, por lo que son dos nombres para el mismo objeto `1` que es de tipo entero.
* Posteriormente, se crea el nuevo objeto `5.0`, un flotante, y se le da el nombre `b`; en ese momento `a` y `b` hacen referencia a dos objetos diferentes y sucede que:
    * el contenido de `b` es `5.0`,
    * `b` tiene un identificador diferente al de `a`
    * y `b` ahora es de tipo flotante.

Esta conceptualizaci√≥n de objetos y sus nombres es muy importante cuando se manejan estructuras de datos m√°s complejas.

<div class="alert alert-block alert-info">

<b>Nota</b>. 

<font color="Black">
    
Usaremos el t√©rmino **variable** para referirnos a los nombres de los **objetos**. Cuando sea conveniente usaremos el t√©rmino **objeto**. 
</font>
</div>

## Definici√≥n de varios nombres a la vez.

La siguiente declaraci√≥n genera tres nombres para el mismo valor `25`.

In [16]:
x = y = z = 25

In [17]:
print(x, type(x), id(x))
print(y, type(y), id(y))
print(z, type(z), id(z))

25 <class 'int'> 94882529783464
25 <class 'int'> 94882529783464
25 <class 'int'> 94882529783464


Observa que se cre√≥ el objeto `25` de tipo `<class 'int'>` y los nombres `x`, `y` y `z` son nombres diferentes para el mismo objeto, lo cual se verifica observando que el identificador de cada variable es el mismo.

<div class="alert alert-block alert-success">

### Ejercicio 3.

<font color="Black">
    
En la siguiente celda escribe el siguiente c√≥digo:

```python
y = 2.7182
print(x, type(x), id(x))
print(y, type(y), id(y))
print(z, type(z), id(z))
```
<br>

Ejecuta la celda y observa lo que sucede con el contenido, el tipo y el identificador de las variables `x`, `y` y `z`.
</font>
</div>

In [18]:
# Escribe tu c√≥digo
### BEGIN SOLUTION
y = 2.7182
print(x, type(x), id(x))
print(y, type(y), id(y))
print(z, type(z), id(z))
### END SOLUTION

25 <class 'int'> 94882529783464
2.7182 <class 'float'> 139871770617680
25 <class 'int'> 94882529783464


Observa que la variable `y` es de tipo flotante y tiene el valor `2.7182`.


Podemos eliminar el nombre `x` con la funci√≥n `del()`:

In [20]:
del(x)

Ahora ya no es posible hacer referencia al objeto `25` usando el nombre `x`. Si intentamos imprimir `x` se generar√° un error indicando lo anterior:

In [21]:
print(x)

NameError: name 'x' is not defined

Sin embargo, a√∫n es posible hacer referencia al objeto `25` usando el nombre `z`:

In [22]:
print(z, type(z), id(z))

25 <class 'int'> 94882529783464


El objeto `25` ser√° eliminado de la memoria cuando ya no exista un nombre que haga referencia a √©l. Entonces es posible eliminar ese objeto como sigue:

In [23]:
del(z)

In [24]:
# Esto dar√° un error
print(z, type(z), id(z))

NameError: name 'z' is not defined

## Asignaci√≥n m√∫ltiple

Podemos hacer una asignaci√≥n m√∫ltiple de objetos diferentes a variables diferentes, por ejemplo:

In [27]:
x, y, z = "una cadena", 3.141592, 50

In [28]:
print(x, type(x), id(x))
print(y, type(y), id(y))
print(z, type(z), id(z))

una cadena <class 'str'> 139871468780400
3.141592 <class 'float'> 139871770617904
50 <class 'int'> 94882529784264


Como se observa, las variables `x`, `y` y¬†`z` hacen referencia a diferentes objetos de distinto tipo.

<a name="unicode">
    
## Nombres de variables Unicode
</a>

<div class="alert alert-block alert-info">

<b>Unicode</b>. 

<font color="Black">
    
Es un est√°ndar para la codificaci√≥n de caracteres, que permite el tratamiento inform√°tico, la transmisi√≥n y visualizaci√≥n de textos de muchos idiomas y disciplinas t√©cnicas. Unicode intenta tener universalidad, uniformidad y unicidad.  

Unicode define tres formas de codificaci√≥n bajo el nombre UTF (Unicode transformation format): UTF8, UTF16, UTF32. V√©ase https://es.wikipedia.org/wiki/Unicode
</font>
</div>

Python utiliza la codificaci√≥n unicode, podemos saber el tipo de codificaci√≥n como sigue:

In [29]:
# Importamos el m√≥dulo sys
import sys

# Imprimimos el tipo de codificaci√≥n
sys.stdout.encoding 

'UTF-8'

La compatibilidad con UTF-8 en Python significa que se puede leer, escribir y manipular archivos de datos provenientes de fuentes diversas como archivos binarios, bases de datos, APIs web, entre muchas otras; estas fuentes pueden contener texto en diferentes idiomas y codificaciones.

A continuaci√≥n se muestran algunos ejemplos.

In [30]:
# Acentos y caracteres de idiomas en el nombre de variables
M√©xico = "en el ombligo de la luna"
espa√±ol = "lengua romance"
fran√ßais = "langues romanes"
ŒïŒªŒªŒ∑ŒΩŒπŒ∫Œ¨ = "Griego"
–†—É—Å—Å–∫–∏–π = "Ruso"

# S√≠mbolos matem√°ticos
ùúã = 3.1416
‚Ñè = 6.626e-34

Estas variables se pueden usar como cualquier otra, por ejemplo podemos imprimir su contenido, determinar su tipo y su identificador en memoria, y las podemos usar en operaciones:

In [31]:
print(M√©xico, type(M√©xico), id(M√©xico))
print(ùúã, type(ùúã), id(ùúã))
print(2 * ùúã)

en el ombligo de la luna <class 'str'> 139871769541760
3.1416 <class 'float'> 139871770622032
6.2832


Tambi√©n es posible imprimir el caracter unicode y su valor como sigue:

In [32]:
# Imprimimos el valor de la variable ŒïŒªŒªŒ∑ŒΩŒπŒ∫Œ¨
print("ŒïŒªŒªŒ∑ŒΩŒπŒ∫Œ¨ = ", ŒïŒªŒªŒ∑ŒΩŒπŒ∫Œ¨)

ŒïŒªŒªŒ∑ŒΩŒπŒ∫Œ¨ =  Griego


Los c√≥digos Unicode de cada caracter se pueden dar en decimal o hexadecimal, por ejemplo para el s√≠mbolo $\pi$ se tiene el c√≥digo decimal `120587` y hexadecimal `0x1D70B`. La funci√≥n `chr()` convierte el c√≥digo Unicode en el caracter correspondiente:

In [33]:
# C√≥digo hexadecimal del caracter ùúã
chr(0x1D70B)

'ùúã'

In [34]:
# C√≥digo decimal del caracter ùúã
chr(120587)

'ùúã'

La funci√≥n `ord()` obtiene el c√≥digo Unicode de un caracter y lo regresa en decimal:

In [35]:
ord("ùúã")

120587

Tambi√©n es posible obtener m√°s informaci√≥n de los c√≥digos unicode como sigue:

In [36]:
# Importamos el m√≥dulo unicodedata
import unicodedata 

print("ùúã")
print(ord("ùúã"))
print(unicodedata.category("ùúã"))
print(unicodedata.name("ùúã"))

ùúã
120587
Ll
MATHEMATICAL ITALIC SMALL PI


Para m√°s informaci√≥n v√©ase: https://docs.python.org/3/howto/unicode.html

<div class="alert alert-block alert-success">

### Ejercicio 4.

<font color="Black">
    
1. Define la variable `ùúã = 3 + 1/7` y el radio `r = 6378`. Usando estas variables escribe el siguiente c√≥digo, el cual calcula el volumen con la siguiente f√≥rmula $\;\;V = \dfrac{4}{3} \pi r^3 \;\;$:

```python
ùúã = 3 + 1/7
r = 6378
V = 4 / 3 * ùúã * r ** 3
```

</font>
</div>

In [37]:
# Define las variables ùúã y r, y la f√≥rmula
### BEGIN SOLUTION
ùúã = 3 + 1/7
r = 6378
V = 4 / 3 * ùúã * r ** 3
### END SOLUTION

In [39]:
print("ùúã =", ùúã) 
print("r =", r)
print("V =", V)

ùúã = 3.142857142857143
r = 6378
V = 1087218721398.8569


Observa que en la celda anterior se imprime un texto, que es el nombre de la variable y el s√≠mbolo `=`, y posteriormente el contenido de la variable.

## Nombres inv√°lidos para variables

Los siguientes ejemplos **NO SON V√ÅLIDOS** para el nombre de variables. Al ejecutar las celdas se obtendr√° un error en cada una de ellas.

In [40]:
1luis = 20      # No se puede iniciar con un n√∫mero

SyntaxError: invalid decimal literal (953519616.py, line 1)

In [41]:
luis$ = 8.2323  # No puede contener caracteres especiales

SyntaxError: invalid syntax (3857869541.py, line 1)

In [42]:
for = 35        # Algunos nombres ya est√°n reservados

SyntaxError: invalid syntax (2521306807.py, line 1)

### Palabras reservadas.

Como vimos en la celda anterior, no es posible usar las palabras reservadas de Python para nombrar variables. La lista de palabras reservadas se puede consultar con la siguiente expresi√≥n:

In [43]:
help("keywords")


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 

